# janela
LARGURA_TELA = 800
ALTURA_TELA = 600
TITULO_JANELA = "Tux: Fragmentos de Gelo"
FPS = 60

# cores
COR_FUNDO = (20, 20, 30)
COR_TUX = (0, 150, 255)

# jogador
PLAYER_LARGURA = 50
PLAYER_ALTURA = 50
PLAYER_VIDA_INICIAL = 3
PLAYER_VELOCIDADE = 4
PLAYER_GRAVIDADE = 0.8
PLAYER_FORCA_PULO = -15

# limites do cenario
CHAO_Y = 500
LIMITE_ESQUERDA = 0
LIMITE_DIREITA = 750

# pontuação
PONTOS_POR_INIMIGO = 10
PONTOS_POR_FASE = 50